name: debugger

on:
  pull_request:

jobs:
  frontend:
    name: debug
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ''

      - name: Check for frontend file changes
        uses: getsentry/paths-filter@v2
        id: changes
        with:
          token: ${{ github.token }}
          filters: .github/file-filters.yml

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: getsentry token
        uses: getsentry/action-github-app-token@v1
        id: getsentry
        with:
          app_id: ${{ secrets.SENTRY_INTERNAL_APP_ID }}
          private_key: ${{ secrets.SENTRY_INTERNAL_APP_PRIVATE_KEY }}

      # Notify getsentry only if there were frontend files changed
      - name: Dispatch getsentry frontend tests
        uses: actions/github-script@v3
        with:
          github-token: ${{ steps.getsentry.outputs.token }}
          script: |
            github.actions.createWorkflowDispatch({
              owner: 'getsentry',
              repo: 'getsentry',
              workflow_id: 'js-build-and-lint.yml',
              ref: 'master',
              inputs: {
                'skip': "${{ steps.changes.outputs.frontend != 'true' }}",
                'sentry-sha': '${{ github.event.pull_request.head.sha }}',
              }
            })
