name: javascript
on: push
jobs:
    build:
      name: eslint
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v1

        - name: install dev deps
          run: npm install --only=dev

        - name: eslint
          run: yarn github-actions-eslint-annotator
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            PARTIAL_LINTING: true # default: false, only works on PRs
