name: javascript
on: push
jobs:
    build:
      name: eslint
      runs-on: ubuntu-latest
      steps:
        - name: eslint
          run: npx github-actions-eslint-annotator
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            PARTIAL_LINTING: true # default: false, only works on PRs
