# This creates a "meta" status that reflects what we deem as "required" checks
# This allows us to define a single requirement for Freight instead of each individual job name.
name: required checks

on:
  # The reason we use workflow_run is because other, more relevant, events (e.g. `status` or `check_run`)
  # will not get triggered by GHA workflows.
  workflow_run:
    workflows: ["backend lint", "backend \[py3.6\]"]
    types:
      - completed

jobs:
  # lint backend, backend test py3.6, backend test, typescript and lint, webpack, sentry backend test, sentry cli test
  verify-required-checks:
    name: verify required checks
    runs-on: ubuntu-16.04

    steps:
      # Need to checkout for `./scripts/getsentryRequiredJobs.js`
      - uses: actions/checkout@v2

      - name: Verify required check runs
        uses: actions/github-script@v3
        with:
          script: |
            const {verifyRequiredJobs} = require(`${process.env.GITHUB_WORKSPACE}/.github/workflows/scripts/getsentryRequiredJobs`)
            const requiredJobs = require(`${process.env.GITHUB_WORKSPACE}/.github/requiredJobs`)

            await verifyRequiredJobs({
              github,
              context,
              checkName: 'getsentry required checks',
              requiredJobs,
            });


